version: 2
jobs:
  u18.04-bionic:
    docker:
      - image: ubuntu:bionic
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install software-properties-common -y
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            DEBIAN_FRONTEND=noninteractive apt-get install libmrpt-dev cmake build-essential -y
      - checkout
      - run:
          name: Generate cmake files
          command: |
            cmake -H. -Bbuild
      - run: make -C build
#      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
#      - run: make gcov -C build
#      - run: make -C build
#      - run: bash <(curl -s https://codecov.io/bash) -X gcov -y .codecov.yml -s build
  u20.04-focal:
    docker:
      - image: ubuntu:focal
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install software-properties-common -y
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            DEBIAN_FRONTEND=noninteractive apt-get install libmrpt-dev cmake build-essential -y
      - checkout
      - run:
          name: Generate cmake files
          command: |
            cmake -H. -Bbuild
      - run: make -C build
workflows:
  version: 2
  build:
    jobs:
      - u18.04-bionic
      - u20.04-focal
